name: Lint and Test

on: push

jobs:
  clj_style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: 0918nobita/setup-cljstyle@v0.2.0
        with:
          cljstyle-version: 0.14.0
      - run: cljstyle check --report -v

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: jdk
          architecture: x64

      - uses: DeLaGuardo/setup-clojure@master
        with:
          lein: '2.9.4'

      - name: Cache dependencies
        uses: toyokumo/cache@main
        with:
          path: |
            ~/.m2
            ~/.lein
          key: clj-cache-${{ hashFiles('**/project.clj') }}
          restore-keys: |
            clj-cache-

      - name: Run tests
        run: lein test

